### ISSUE TITLE
Support development branches

### ISSUE THREAD

**Issue by niemeyer** [niemeyer/gopkg#25]
This is a pain point that has shown up a few times and I think we should address, so here is the rationale and a candidate plan for it.

In a few cases I wanted to share an unstable sneak peak of the next API version. The most recent case at hand was the [gopkg.in/qml.v0 => v1 migration](http://blog.labix.org/2014/08/13/announcing-qml-v1-for-go). The problem was that the new project API version was still being worked on at a fast pace, breaking every day, and at the same time there were people interested in experimenting and helping out on the new API. This forced the early release of gopkg.in/qml.v1, with an unstable qml.v1/gl subpackage, which is not great and kills the expectation of stability that we want to create. This also sounds like a common problem, that we should address for everybody with a well known pattern rather than struggling every time.

So the current plan is to introduce support for `vN-dev` selector in URLs, which map to the `vN*-dev` tag/branch. In the example cited, this would allow the development of v1-dev publicly, while clearly marking the content as in-development. Once the daily breakages stop, it can be tagged/copied into the `v1` release appropriately and as usual.

Please feel free to provide feedback here. If there are no major uncovered points, I'll work on this soon.

**Comment by shurcooL** [comment]
If someone wants to import the "latest in-development version" of a given package, could they not simply import the root source at github.com/user/repo?

I suppose there'd be complications if the package imports subpackages (within same repo) that are versioned. In that case, I just want to say +1 to the issue and that some solution would be helpful.

**Comment by nathany** [comment]
Subpackages cause complications either way.

Looking at the amz library, the v2-dev branch still imports packages from v1, mixing code from both branches. I suspect it hasn't been fixed because of this issue. It's easy enough to change those imports.

amz has a default branch of v1. This means cloning the GitHub url will check out v1 for you. But it also means pull requests are opened against v1 by default. It might be more appropriate if they opened against v2-dev by default, as a working branch. The maintainers could choose whether to back port a change to v1. Of course this is really up to them, and master vs. v2-dev doesn't make much difference.

Due to #20, amz must still maintain a master branch even though it's not really needed. That adds some confusion to the whole thing.

I agree that v2-dev could be more clear to users of the package than master. For contributors, I'm less sure, perhaps they are equivalent?

**Comment by niemeyer** [comment]
@nathany Indeed, once this feature goes live (very soon!), the best approach is to hold the vN-unstable branch as the development focus where activities happen, and have a vN release branch that is tagged/merged to for release of the changes.

**Comment by shurcooL** [comment]
What about `master` branch? Will it still be necessary to have one for gopkg.in to work despite it being unused and irrelevant? Can master be used as vN+1unstable branch?

**Comment by niemeyer** [comment]
The suffix was changed to "-unstable" in the implementation, as that's significantly more clear than "-dev" (we're all _devs_ doing _dev_ all the time).

**Comment by niemeyer** [comment]
@shurcooL That's issue #20 which will be fixed. No, vN-unstable maps to vN-unstable, which seems very clear and straightforward.

**Comment by shurcooL** [comment]
Thanks.

**Comment by AlekSi** [comment]
@niemeyer May you document "-unstable" suffix at http://labix.org/gopkg.in (redirected from http://gopkg.in)?
