### ISSUE TITLE
Popular packages

### ISSUE THREAD

**Issue by montanaflynn** [niemeyer/gopkg#38]
I think it would be a big improvement if http://gopkg.in showcased popular packages that are conforming to the versioning standards and being heavily used. This would help adoption and give incentives to package maintainers to share the word about gopkg.in.

**Comment by niemeyer** [comment]
Sounds like a fine idea to me.

**Comment by montanaflynn** [comment]
Here's a few I found recently, however I think by checking server logs you should be able to get a better picture of how many packages are being used with gopkg.in and which are the most popular.

https://github.com/tylerb/graceful
https://github.com/stretchr/testify

**Comment by fervic** [comment]
Hi, this sounds really good and I would like to add generating some sort of color coded badge like those of the CI tools (e.g. ![Build Status](https://travis-ci.org/jessevdk/go-flags.svg?branch=master)) but in this case showing info about when the last tag was created in relation to code changes in master or I don't know, something that reflects how much you can rely on a _"gopkg.in/..."_ URL instead of using a _"github.com/..."_ URL

I say this because there are some projects out there that show activity but generated the last tag more than two years ago, for example: https://github.com/jessevdk/go-flags

**Comment by nathany** [comment]
@fervic See #18 regarding a badge.

**Comment by niemeyer** [comment]
Just going over some old issues here and cleaning things up. Given the "recent" features added to the Go tool, it's unlikely that we'll see further development of features on gopkg.in itself.
