### ISSUE TITLE
beta version 0.1 and 0.2

### ISSUE THREAD

**Issue by avelino** [niemeyer/gopkg#57]
@nuveo maintains a software called [pREST](https://github.com/nuveo/prest) that this in the beta version, today we generate version 0.2 that is not compatible with 0.1, how to deal with this case in gopkg?

- gopkg.in/nuveo/prest.v0.1 (not working)
- gopkg.in/nuveo/prest.v0.2 (not working)
- gopkg.in/nuveo/prest.v0 (call branch v0.2 working)

**Comment by niemeyer** [comment]
If you follow [semantic versioning](http://semver.org), v0 is allowed to break compatibility and people will just have to update. That's used for highly unstable software that you don't want to promise any guarantees just yet.

That said, you seem to be bothered by the breakage, which implies that's now quite what you expected or intended to offer. In those cases, the common convention in semantic versioning and in good part of the software world is to respect compatibility across version updates when you're just bumping a minor version. That's why we support v0, v1, etc as separate URLs. People using one of those is guaranteed to stay safe since the author shouldn't be breaking backwards compatibility inside the major.

There are some more details in this post which will probably be an interesting read: 

https://blog.labix.org/2015/01/14/no-minor-versions-in-go-import-paths
