### ISSUE TITLE
fsnotify breakage

### ISSUE THREAD

**Issue by nkovacs** [niemeyer/gopkg#61]
Can we please have a temporary workaround in gopkg.in to fix the fsnotify breakage?
I can't just rewrite all the imports in all my branches and tags and update all the vendored packages (assuming they have been fixed at all).

**Comment by niemeyer** [comment]
Just complete clarity, this issue was completely unrelated to gopkg.in. The project had its organization renamed, which is a pretty bad idea for Go packages, and double bad if you're not keeping ownership of the old location. This means it only worked while GitHub had the redirection setup. Once someone else (anyone!) registered the old project, they would get all the code imports.

With all that said, I've just deployed a redirection to fix all clients of this package. So this:

https://gopkg.in/fsnotify.v1

will now point to this:

https://gopkg.in/fsnotify/fsnotify.v1

Please don't trust that sort of manual change to be happening routinely.

**Comment by nkovacs** [comment]
Thank you.

**Comment by nkovacs** [comment]
It's not working:

```
 go get -v gopkg.in/fsnotify
Fetching https://gopkg.in/fsnotify?go-get=1
Parsing meta tags from https://gopkg.in/fsnotify?go-get=1 (status code 404)
package gopkg.in/fsnotify: unrecognized import path "gopkg.in/fsnotify" (parse https://gopkg.in/fsnotify?go-get=1: no go-import meta tags ())
```

https://gopkg.in/fsnotify?go-get=1

**Comment by niemeyer** [comment]
That URL is wrong (missing .v1), but the same error is happening on the real one. I'll fix that today.

**Comment by niemeyer** [comment]
My apologies.. I got the redirect logic wrong the first time. This should be fixed now.

**Comment by nkovacs** [comment]
Thank you, it works now.
